lib/platform_web/router.ex
defmodule PlatformWeb.Router do
  use PlatformWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlatformWeb.PlayerAuthController, repo: Platform.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlatformWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/games/:slug", GameController, :play
    resources "/players", PlayerController
    resources "/sessions", PlayerSessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  scope "/api", PlatformWeb do
    pipe_through :api

    resources "/players", PlayerApiController, except: [:new, :edit]
    resources "/games", GameController, except: [:new, :edit]
  end
end

lib/platform_web/views/layout_view.ex
defmodule PlatformWeb.LayoutView do
  use PlatformWeb, :view
end

lib/platform_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Platform</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container-fluid">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @current_user do %>
              <p class="navbar-text"> 
                Signed in as 
                <strong>
                  <%= if @current_user.display_name do %>
                    <%= link @current_user.display_name, to: player_path(@conn, :edit, @current_user) %>
                  <% else %>
                    <%= link @current_user.username, to: player_path(@conn, :edit, @current_user) %>
                  <% end %>
                </strong>
              </p>
              <%= link "Sign Out", to: player_session_path(@conn, :delete, @current_user), method: "delete", class: "btn navbar-btn btn-danger" %>
            <% else %>
              <%= link "Sign Up", to: player_path(@conn, :new), class: "btn navbar-btn btn-success" %>
              <%= link "Sign In", to: player_session_path(@conn, :new), class: "btn navbar-btn btn-primary" %>
              <% end %>
          </ul>
        </nav>
        <%= link "Platform", to: page_path(@conn, :index), class: "logo" %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>